blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/SeanDictionary/SageMath-for-VScode#readme
    about: Check the README for usage instructions and troubleshooting
  - name: Discussions
    url: https://github.com/SeanDictionary/SageMath-for-VScode/discussions
    about: Ask questions and discuss ideas
